### ISSUE TITLE
Modem not functioning after flashing

### ISSUE THREAD

**Issue by thududoo** [stanislawrogasik/Pixel2XL-VoLTE-VoWiFi#2]
I am not using a pixel but I tried the method and everything seems works fine. However the first time I flashed it nothing happend. After the second run, I can register IMS and wifi calling but I cannot get the modem work. There is no way to search a signal and everything seems glitchy. The phone setting is flashing between no sim card and no serviece, and the *#*#4646#*#* menu is laggy and nothing works. The Mobile Radio Power toggle is auto switching every 5 sec but if I take the sim card out, everything goes fine. 
Any idea what's going on here?

**Comment by stanislawrogasik** [comment]
Hi @thududoo 

What device do you have? 
It may be due to flashing MBN which is not dedicated for yours modem.

As an example, if I would flash Pixel 5 MBN over Pixel 2 XL it would also do not work.
You need to pick proper file from a different phone with the same CPU. So if you have a Snap835 then look for devices with Snap835 and try to extract MBNs from them
